---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    - AFTER_SCRIPT="true"
    - BEFORE_SCRIPT="true"
    - TEST_COMMAND=""
  matrix:
    - EMBER_TRY_SCENARIO=ember-2.3
    - EMBER_TRY_SCENARIO=ember-lts-2.4
    - EMBER_TRY_SCENARIO=ember-2.5
    - EMBER_TRY_SCENARIO=ember-2.6
    - EMBER_TRY_SCENARIO=ember-2.7
    - EMBER_TRY_SCENARIO=ember-lts-2.8
    - EMBER_TRY_SCENARIO=ember-2.9
    - EMBER_TRY_SCENARIO=ember-2.10
    - EMBER_TRY_SCENARIO=ember-lts-2.12
    - EMBER_TRY_SCENARIO=ember-2.13
    - EMBER_TRY_SCENARIO=ember-release
    - EMBER_TRY_SCENARIO=ember-beta
    - EMBER_TRY_SCENARIO=ember-canary
    - EMBER_TRY_SCENARIO=ember-lts-2.4-bs4
    - EMBER_TRY_SCENARIO=ember-lts-2.8-bs4
    - EMBER_TRY_SCENARIO=ember-lts-2.12-bs4
    - EMBER_TRY_SCENARIO=ember-release-bs4
    - EMBER_TRY_SCENARIO=ember-beta-bs4
    - EMBER_TRY_SCENARIO=fastboot-addon-tests
    - EMBER_TRY_SCENARIO=node-tests
    - EMBER_TRY_SCENARIO=ember-release BEFORE_SCRIPT="ember sauce:connect" AFTER_SCRIPT="ember sauce:disconnect" TEST_COMMAND="ember test --config-file testem.sauce.js --test-port 7000"

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm config set spin false
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm --version
  - yarn --version
  - google-chrome-stable --version

install:
  - yarn install
  # temporary workaround for https://github.com/yarnpkg/yarn/issues/3485
  - npm rebuild node-sass

script:
  - ember try:one $EMBER_TRY_SCENARIO --skip-cleanup --- $TEST_COMMAND

before_script:
  - $BEFORE_SCRIPT

after_script:
  - $AFTER_SCRIPT

addons:
    code_climate:
        repo_token: de4cedac171d091882efe2719ae10fbdb5e5054077123f8455b251719973a606
