---
language: node_js
node_js:
  # revert to node 4 once https://github.com/kybishop/ember-popper/pull/45 is merged and released
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    - AFTER_SCRIPT="true"
    - BEFORE_SCRIPT="true"
    - TEST_COMMAND=""
    - SAUCE_USERNAME="ember-bootstrap"
    - SAUCE_ACCESS_KEY="16ef42b7-b940-4a05-bb1e-9e3fef3bf634"
    # greenkeeper
    - secure: QKF4gJdgWzwTk6eMMVZvP+FBs7Ab3fFYnXfLHHNbQOkIVrwO0D7ns3Umtea9lMIt1bQOq6VHmcsf/BUhi4L+oLEXAZ827GShDKhojqGIDg4poaA9kECtUzsIUnKB+bYkvadRsuUP0KjxNbSM7nVchUDTgRvt0OZZ0rP3q4/oQC8=

  matrix:
    - EMBER_TRY_SCENARIO=ember-2.3
    - EMBER_TRY_SCENARIO=ember-lts-2.4
    - EMBER_TRY_SCENARIO=ember-lts-2.8
    - EMBER_TRY_SCENARIO=ember-lts-2.12
    - EMBER_TRY_SCENARIO=ember-2.13
    - EMBER_TRY_SCENARIO=ember-release
    - EMBER_TRY_SCENARIO=ember-beta
    - EMBER_TRY_SCENARIO=ember-canary
    - EMBER_TRY_SCENARIO=ember-lts-2.8-bs4
    - EMBER_TRY_SCENARIO=ember-lts-2.12-bs4
    - EMBER_TRY_SCENARIO=ember-release-bs4
    - EMBER_TRY_SCENARIO=fastboot-addon-tests
    - EMBER_TRY_SCENARIO=node-tests
    - EMBER_TRY_SCENARIO=ember-default BEFORE_SCRIPT="ember sauce:connect" AFTER_SCRIPT="ember sauce:disconnect" TEST_COMMAND="ember test --config-file testem.sauce.js --test-port 7000"

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

branches:
  only:
    - master

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm config set spin false
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm --version
  - yarn --version
  - google-chrome-stable --version
  - yarn global add greenkeeper-lockfile@1

install:
  - yarn install

script:
  - ember try:one $EMBER_TRY_SCENARIO --skip-cleanup --- $TEST_COMMAND

before_script:
  - greenkeeper-lockfile-update
  - $BEFORE_SCRIPT

after_script:
  - $AFTER_SCRIPT
  - greenkeeper-lockfile-upload

addons:
    code_climate:
        repo_token: de4cedac171d091882efe2719ae10fbdb5e5054077123f8455b251719973a606