---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules
    - $HOME/.yarn-cache
    - $HOME/.cache # includes bowers cache

env:
  - EMBER_TRY_SCENARIO=ember-2.3
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-2.5
  - EMBER_TRY_SCENARIO=ember-2.6
  - EMBER_TRY_SCENARIO=ember-2.7
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-2.9
  - EMBER_TRY_SCENARIO=ember-2.10
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-lts-2.4-bs4
  - EMBER_TRY_SCENARIO=ember-lts-2.8-bs4
  - EMBER_TRY_SCENARIO=ember-release-bs4
  - EMBER_TRY_SCENARIO=ember-beta-bs4
  - EMBER_TRY_SCENARIO=fastboot-addon-tests

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add phantomjs-prebuilt
  - yarn global add bower
  - yarn --version
  - bower --version
  - phantomjs --version

install:
  - yarn install
  - bower install

script:
  - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

addons:
    code_climate:
        repo_token: de4cedac171d091882efe2719ae10fbdb5e5054077123f8455b251719973a606
